import { Injectable, signal, computed } from '@angular/core';

export type Language = 'es' | 'en';

const ES_DICT = {
  common: {
    search: 'Buscar...',
    actions: 'Acciones',
    status: 'Estado',
    save: 'Guardar',
    cancel: 'Cancelar',
    loading: 'Cargando...',
    error: 'Error',
    success: 'Éxito',
    warning: 'Advertencia',
    noResults: 'No se encontraron resultados',
    doctor: 'Médico',
    birthDate: 'Fecha de Nacimiento',
    username: 'Nombre de Usuario',
    confirm: 'Confirmar',
    edit: 'Editar',
    delete: 'Eliminar',
    view: 'Ver',
    male: 'Masculino',
    female: 'Femenino',
    other: 'Otro',
    filters: 'Filtros',
    advancedFilters: 'Filtros Avanzados',
    clearFilters: 'Limpiar Filtros',
    resultsOf: 'Mostrando {{count}} de {{total}} registros',
    select: 'Seleccione...',
    back: 'Volver',
    dashboard: 'Panel Principal',
    active: 'Activo',
    inactive: 'Inactivo'
  },
  auth: {
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    logout: 'Cerrar Sesión',
    logoutConfirm: '¿Desea cerrar sesión?',
    logoutText: 'Tendrá que ingresar sus credenciales de nuevo.',
    logoutYes: 'Sí, salir',
    logoutCancel: 'Cancelar',
    welcome: '¡Bienvenido!',
    email: 'Email',
    password: 'Contraseña'
  },
  video_history: {
    sidebar: 'Videoconsultas',
    title: 'Historial de Videoconsultas',
    subtitle: 'Consulte y gestione el registro histórico de sus videollamadas médicas.',
    refresh: 'Refrescar',
    loadError: 'No se pudo cargar el historial de videoconsultas.',
    noResults: 'Sin Videoconsultas',
    noResultsDesc: 'Aún no tiene registros de videollamadas. Puede agendar una nueva consulta desde el módulo de citas.',
    goToAppointments: 'Ir a Mis Citas',
    patient: 'Paciente',
    doctor: 'Médico',
    duration: 'Duración',
    consultNotes: 'Notas de la Consulta',
    downloadReport: 'Descargar Informe',
    joinCall: 'Unirse a la Llamada',
    status: {
      scheduled: 'Programada',
      active: 'Activa',
      completed: 'Completada',
      cancelled: 'Cancelada'
    },
    reportTitle: 'INFORME DE VIDEOCONSULTA MÉDICA',
    telemedPlatform: 'Plataforma de Telemedicina',
    sessionDetails: 'DETALLES DE LA SESIÓN',
    treatingDoctor: 'Médico Tratante',
    date: 'Fecha',
    minutes: 'minutos',
    clinicalNotes: 'HALLAZGOS Y NOTAS CLÍNICAS',
    generatedOn: 'Informe generado el'
  },
  team: {
    sidebar: 'Gestión de Equipo',
    title: 'Personal de la Clínica',
    subtitle: 'Gestión de miembros y roles del equipo administrativo y médico',
    addMember: 'Añadir Miembro',
    newMember: 'Nuevo Miembro del Equipo',
    member: 'Miembro',
    role: 'Rol',
    selectRole: 'Seleccione un rol',
    license: 'Número de Licencia',
    gender: 'Género',
    invitationButton: 'Enviar Invitación',
    noMembers: 'No hay miembros registrados aún.',
    messages: {
      loading: 'Procesando...',
      success: 'Miembro añadido y correo de bienvenida enviado.',
      confirmDelete: '¿Eliminar miembro?',
      confirmDeleteText: 'El usuario perderá el acceso a la plataforma.',
      yesDelete: 'Confirmar Eliminación'
    }
  },
  billing: {
    sidebar: 'Mi Suscripción',
    title: 'Mi Suscripción y Facturación',
    subtitle: 'Gestione su plan, métodos de pago e historial de transacciones',
    updatePlan: 'Actualizar Plan',
    timeRemaining: 'Tiempo restante',
    days: 'días',
    expiresOn: 'Vence el:',
    reminderNotice: 'Recuerde mantener sus pagos al día para evitar la interrupción del servicio.',
    paymentHistory: 'Historial de Pagos',
    noPayments: 'No se encontraron pagos recientes en su historial.',
    table: {
      date: 'Fecha',
      concept: 'Concepto',
      method: 'Método / Banco',
      amount: 'Monto',
      status: 'Estado',
      receipt: 'Recibo / PDF'
    }
  },
  payments: {
    title: 'Control de Pagos',
    subtitle: 'Gestión de facturación y estados de cuenta',
    newPayment: 'Nueva Transacción',
    export: 'Exportar Reporte',
    reference: 'Referencia',
    patient: 'Paciente',
    concept: 'Concepto',
    amount: 'Monto',
    fecha: 'Fecha',
    collect: 'Cobrar',
    receipt: 'Recibo',
    pending: 'Pendiente',
    paid: 'Pagado',
    doctorConsultation: 'Consulta / Médico',
    generalPayment: 'Pago General',
    edit: 'Editar Pago',
    delete: 'Eliminar Pago',
    registerTitle: 'Registrar Nuevo Pago',
    editTitle: 'Editar Pago de Cita',
    payCurrency: 'Moneda del Pago',
    bankPlatform: 'Banco / Plataforma',
    updateReceipt: 'Actualizar Comprobante (Opcional)',
    hasAttachment: 'Este pago ya tiene un comprobante adjunto.',
    selectAppointment: 'Seleccionar Cita',
    method: 'Método de Pago',
    select: 'Seleccione una opción',
    bankPlatformPlaceholder: 'Ej: Banesco, Mercantil, Zelle...',
    refPlaceholder: 'Número de comprobante o referencia',
    payDate: 'Fecha del Pago',
    attachReceipt: 'Adjuntar Comprobante',
    saveChanges: 'Guardar Cambios',
    confirmDelete: '¿Eliminar Pago?',
    confirmDeleteText: 'Esta acción no se puede deshacer.',
    yesDelete: 'Sí, eliminar',
    deleted: 'Eliminado',
    deletedMsg: 'El pago ha sido eliminado.',
    updated: '¡Actualizado!',
    updatedMsg: 'El pago ha sido actualizado correctamente.',
    viewReceipt: 'Ver Recibo / Comprobante',
    subscriptionPayment: 'Registrar Pago de Suscripción (Plan)',
    patientPayment: 'Registrar Pago de Paciente',
    selectRole: 'Tipo de Pago',
    onboardingTitle: 'Pago de Suscripción',
    onboardingSuccess: 'Pago registrado con éxito.',
    onboardingRegister: 'Ahora, complete su registro para activar su cuenta.',
    goToRegister: 'Ir a Registro',
    onboardingExisting: 'Pago de renovación registrado con éxito. Su plan se activará en breve.'
  },
  medical_history: {
    title: 'Historia Médica Digital',
    subtitle: 'Expediente clínico completo y cronológico del paciente',
    selectPatient: 'Seleccione un paciente para ver su historia',
    id: 'Cédula/ID',
    phone: 'Teléfono',
    gender: 'Género',
    newRecord: 'Nueva Consulta / Evolución',
    changePatient: 'Cambiar Paciente',
    physicalExam: 'Examen Físico / Motivo',
    treatment: 'Tratamiento Sugerido',
    diagnosis: 'Diagnóstico Clínico',
    indications: 'Indicaciones Médicas',
    save: 'Guardar Consulta',
    print: 'Imprimir Informe',
    export: 'Exportar Historia',
    examPlaceholder: 'Signos vitales, hallazgos físicos...',
    treatmentPlaceholder: 'Medicamentos y procedimientos...',
    indicationsPlaceholder: 'Reposo, dieta, cuidados...',
    medicalLeave: 'Reposo Médico / Constancia',
    leaveDays: 'Días de reposo',
    startDate: 'Fecha Inicio',
    endDate: 'Fecha Fin (Estimada)',
    tabs: {
      consultations: 'Consultas',
      labs: 'Laboratorio',
      treatments: 'Tratamientos'
    },
    prescription: {
      title: 'Receta Médica (Rp)',
      search: 'Buscar medicamento...',
      drug: 'Medicamento',
      dosage: 'Dosis',
      frequency: 'Frecuencia',
      duration: 'Duración',
      empty: 'No hay medicamentos agregados a la receta'
    }
  },
  sidebar: {
    medicalManagement: 'GESTIÓN MÉDICA',
    appointments: 'Citas Médicas',
    history: 'Historial Médico',
    patients: 'Pacientes',
    lab: 'Laboratorio',
    medicalStaff: 'PERSONAL MÉDICO',
    doctors: 'Doctores',
    nurses: 'Enfermería',
    drugGuide: 'Guía Farmacéutica',
    administration: 'ADMINISTRACIÓN',
    staff: 'Mi Personal',
    payments: 'Control de Pagos',
    config: 'CONFIGURACIÓN',
    bulkData: 'Carga Masiva',
    myTeam: 'Gestión de Equipo',
    billing: 'Mi Suscripción',
    dashboard: 'Panel Principal',
    labCatalog: 'Catálogo Lab',
    branding: 'Imagen Corporativa'
  },
  navbar: {
    updateInfo: 'Actualizar Información',
    changePassword: 'Cambiar Contraseña',
    logout: 'Cerrar Sesión',
    updateRate: 'Actualizar Tasa BCV',
    rateHint: 'Tasa oficial del Banco Central'
  },
  roles: {
    SUPERADMIN: 'Super Administrador',
    ADMINISTRATIVE: 'Personal Administrativo',
    DOCTOR: 'Médico Especialista',
    NURSE: 'Enfermería',
    PATIENT: 'Paciente',
    RECEPTIONIST: 'Recepcionista'
  },
  drug_guide: {
    title: 'Guía Farmacéutica Digital',
    subtitle: 'Vademécum completo de medicamentos y posología',
    newDrug: 'Nuevo Medicamento',
    vademecumLabel: 'Consulta Externa Vademécum',
    vademecumDesc: 'Enlace directo a la base de datos farmacéutica oficial.',
    vademecumLink: 'Ir al Vademécum',
    searchPlaceholder: 'Buscar por nombre, principio activo...',
    search: 'Buscar',
    allCategories: 'Todas las categorías',
    noResults: 'No se encontraron medicamentos',
    noResultsHint: 'Intente con otro término o agregue uno nuevo a la base de datos.',
    results: 'resultados',
    validation: 'Por favor complete los campos obligatorios',
    savedOk: 'Medicamento guardado exitosamente',
    confirmDelete: 'Eliminar Medicamento',
    confirmDeleteText: '¿Está seguro de eliminar {{name}}? Esta acción no se puede deshacer.',
    yes: 'Sí, eliminar',
    no: 'Cancelar',
    deletedOk: 'Medicamento eliminado exitosamente',
    noCategory: 'Sin categoría',
    table: {
      commercial: 'Nombre Comercial',
      generic: 'Nombre Genérico',
      components: 'Componentes',
      presentation: 'Presentación',
      category: 'Categoría',
      actions: 'Acciones'
    },
    detail: {
      edit: 'Editar',
      close: 'Cerrar',
      presentation: 'Presentación',
      category: 'Categoría',
      components: 'Componentes Activos',
      indications: 'Indicaciones',
      posology: 'Posología',
      contraindications: 'Contraindicaciones',
      adverseReactions: 'Reacciones Adversas',
      precautions: 'Precauciones',
      noSpecified: 'No especificado'
    },
    form: {
      create: 'Nuevo Medicamento',
      edit: 'Editar Medicamento',
      commercial: 'Nombre Comercial',
      commercialPlaceholder: 'Ej: Panadol',
      generic: 'Nombre Genérico',
      genericPlaceholder: 'Ej: Paracetamol',
      components: 'Componentes Activos',
      componentsPlaceholder: 'Ej: Acetaminofén 500mg',
      componentsHint: 'Principios activos separados por coma',
      presentation: 'Presentación',
      presentationPlaceholder: 'Ej: Tabletas 500mg',
      category: 'Categoría',
      categoryPlaceholder: 'Seleccione o escriba una categoría',
      indications: 'Indicaciones',
      indicationsPlaceholder: 'Para qué sirve este medicamento...',
      posology: 'Posología',
      posologyPlaceholder: 'Dosis recomendada y frecuencia...',
      contraindications: 'Contraindicaciones',
      contraindicationsPlaceholder: 'Cuándo no debe usarse...',
      adverseReactions: 'Reacciones Adversas',
      adverseReactionsPlaceholder: 'Efectos secundarios conocidos...',
      precautions: 'Precauciones',
      precautionsPlaceholder: 'Advertencias y precauciones...',
      cancel: 'Cancelar',
      save: 'Guardar',
      create_btn: 'Crear'
    }
  },
  dashboard: {
    controlPanel: 'Panel de Control',
    welcome: 'Bienvenido de nuevo',
    reportBtn: 'Descargar Reporte',
    newAppointment: 'Nueva Cita',
    activity: 'Actividad de Citas',
    upcoming: 'Próximas Citas',
    days7: 'Últimos 7 días',
    stats: {
      totalPatients: 'Total Pacientes',
      income: 'Ingresos Totales',
      pending: 'Citas Pendientes',
      videoCalls: 'Video Llamadas',
      inPerson: 'Citas Presenciales',
      appointments: 'Citas',
      specialtyBreakdown: 'Distribución por Especialidad',
      incomeAnalysis: 'Análisis de Ingresos',
      daily: 'Ingreso Diario',
      weekly: 'Ingreso Semanal',
      monthly: 'Ingreso Mensual',
      today: 'Citas Hoy',
      patients: 'Pacientes Totales',
      video: 'Videoconsultas (Mes)',
      incomeUSD: 'Ingresos USD (Mes)',
      incomeBs: 'Ingresos Bs (Mes)'
    },
    specialties: {
      pediatrics: 'Pediatría',
      general: 'Medicina General',
      dentistry: 'Odontología',
      cardiology: 'Cardiología',
      gynecology: 'Ginecología',
      traumatology: 'Traumatología',
      dermatology: 'Dermatología',
      neurology: 'Neurología',
      ophthalmology: 'Oftalmología',
      psychiatry: 'Psiquiatría'
    },
    report: {
      stat: 'Estadística',
      value: 'Valor',
      title: 'Reporte de Actividad - MedicalCare 888',
      tagline: 'Gestión Clínica Profesional',
      specialtyPerf: 'Rendimiento por Especialidad',
      pending: 'Pend',
      attended: 'Atend'
    },
    export: {
      title: 'Exportar Reporte',
      text: 'Seleccione el formato de descarga'
    },
    redirecting: 'Redirigiendo al módulo de citas...',
    trial: {
      daysRemaining: 'Tu prueba gratuita finaliza en {{days}} días',
      trialDesc: 'Acceso total a todas las funciones premium habilitado.',
      upgradePlan: 'Actualizar Plan Ahora'
    },
    confirmed: 'Confirmada',
    reminderSent: 'Recordatorio Enviado',
    active: 'Activo',
    inactive: 'Inactivo'
  },
  appointments_list: {
    title: 'Agendamiento de Citas',
    subtitle: 'Gestión de consultas y lista de espera',
    newTitle: 'Nueva Cita',
    editTitle: 'Editar Cita',
    today: 'Citas de Hoy',
    all: 'Todas las Citas',
    pending: 'Pendientes',
    completed: 'Completadas',
    cancelled: 'Canceladas',
    table: {
      patient: 'Paciente',
      doctor: 'Médico',
      date: 'Fecha y Hora',
      status: 'Estado',
      reason: 'Motivo'
    },
    actions: {
      confirm: 'Confirmar Asistencia',
      cancel: 'Cancelar Cita',
      reschedule: 'Reprogramar',
      startConsultation: 'Iniciar Consulta'
    },
    filterSpecialty: 'Filtrar por Especialidad',
    whatsappService: 'Servicio de WhatsApp',
    serviceActive: 'Servicio Activo',
    time: 'Hora de la Cita',
    reason: 'Motivo de Consulta',
    reasonPlaceholder: 'Ej: Control Mensual, Chequeo...',
    notes: 'Notas Adicionales',
    videoCall: 'Vídeo Llamada',
    scheduled: 'Citas Programadas',
    whatsappDesc: 'Recordatorios automáticos para sus pacientes',
    tabs: {
      day: 'Hoy',
      week: 'Semana',
      month: 'Mes'
    },
    new: 'Nueva Cita'
  },
  doctors: {
    title: 'Gestión de Especialistas',
    subtitle: 'Listado completo de médicos y profesionales de la salud',
    new: 'Nuevo Doctor',
    searchPlaceholder: 'Buscar por nombre o especialidad...',
    allSpecialties: 'Todas las especialidades',
    specialist: 'Especialista',
    viewProfile: 'Ver Perfil',
    schedule: 'Ver Agenda',
    noResults: 'No se encontraron doctores con los criterios de búsqueda.',
    active: 'Activo',
    inactive: 'Inactivo',
    available: 'Disponible',
    fields: {
      firstName: 'Nombre',
      lastName: 'Apellido',
      email: 'Email',
      phone: 'Teléfono',
      license: 'Licencia Médica',
      specialty: 'Especialidad',
      password: 'Contraseña',
      passwordPlaceholder: 'Mínimo 6 caracteres'
    },
    messages: {
      completeRequired: 'Por favor completa todos los campos',
      created: '¡Doctor Creado!',
      createdMsg: 'El doctor ha sido registrado exitosamente en el sistema.',
      confirmDelete: '¿Eliminar Doctor?',
      confirmDeleteMsg: 'El doctor dejará de tener acceso al sistema.',
      deleteConfirmBtn: 'Eliminar',
      deleted: 'Eliminado',
      deletedMsg: 'El doctor ha sido retirado del sistema.',
      toggleStatus: '¿{action} Doctor?',
      toggleStatusMsg: 'El doctor {name} quedará {status} en el sistema.',
      toggleBypass: '¿{action} Bypass?',
      toggleBypassMsg: 'El doctor {name} {action2} los límites de suscripción.',
      toggleBypassTooltip: 'Bypass de suscripción (VIP)'
    }
  },
  nurses: {
    title: 'Personal de Enfermería',
    subtitle: 'Gestión de turnos y asignaciones de enfermería',
    new: 'Nueva Enfermera',
    table: {
      nurse: 'Enfermera',
      specialty: 'Especialidad',
      shift: 'Turno',
      license: 'Licencia'
    },
    noResults: 'No se encontraron enfermeras.',
    searchPlaceholder: 'Buscar enfermera...',
    allShifts: 'Todos los turnos',
    filters: 'Filtros',
    showing: 'Mostrando',
    of: 'de',
    filtersCleared: 'Filtros Limpiados',
    filtersClearedMsg: 'Se han restablecido todos los filtros de búsqueda.',
    fields: {
      firstName: 'Nombre',
      lastName: 'Apellido',
      email: 'Email',
      phone: 'Teléfono',
      license: 'Número de Licencia',
      shift: 'Turno',
      specialization: 'Especialidad',
      password: 'Contraseña',
      passwordPlaceholder: 'Mínimo 6 caracteres'
    },
    shifts: {
      morning: 'Mañana',
      afternoon: 'Tarde',
      night: 'Noche',
      rotating: 'Rotativo'
    },
    specialties: {
      general: 'Enfermería General',
      icu: 'Cuidados Intensivos',
      pediatrics: 'Pediatría',
      surgery: 'Quirófano',
      emergency: 'Emergencias',
      geriatrics: 'Geriatría',
      neonatology: 'Neonatología',
      oncology: 'Oncología'
    },
    messages: {
      completeRequired: 'Por favor complete todos los campos obligatorios.',
      created: 'Enfermera Creada',
      createdMsg: 'El registro ha sido creado exitosamente.',
      confirmDelete: '¿Estás seguro?',
      confirmDeleteText: 'Esta acción no se puede deshacer.',
      yesDelete: 'Sí, eliminar',
      deleted: 'Eliminado',
      deletedMsg: 'El registro ha sido eliminado.',
      errorDelete: 'No se pudo eliminar el registro.'
    }
  },
  booking: {
    personalInfo: 'Información Personal',
    firstName: 'Nombre',
    lastName: 'Apellido',
    docId: 'Cédula / Pasaporte',
    gender: 'Género',
    phone: 'Teléfono',
    birthDate: 'Fecha de Nacimiento',
    address: 'Dirección',
    appointmentInfo: 'Detalles de la Cita',
    specialty: 'Especialidad',
    doctor: 'Especialista',
    date: 'Fecha de la Cita',
    reason: 'Motivo de Consulta',
    additionalNotes: 'Notas Adicionales (Opcional)',
    submit: 'Agendar Cita Médica',
    successTitle: '¡Cita Agendada!',
    successMsg: 'Tu cita ha sido registrada exitosamente. Recibirás un correo de confirmación.',
    errorTitle: 'Error',
    errorMsg: 'No se pudo agendar la cita. Por favor verifique los datos.',
    placeholders: {
      firstName: 'Ej: Juan',
      lastName: 'Ej: Pérez',
      docId: 'Ej: 12345678',
      phone: 'Ej: 04121234567',
      address: 'Ciudad, Urbanización...',
      reason: 'Ej: Consulta General, Chequeo...',
      notes: 'Cualquier detalle adicional que desee compartir...',
      specialty: 'Selecciona una especialidad',
      doctor: 'Selecciona un especialista'
    }
  },
  lab: {
    title: 'Resultados de Laboratorio',
    subtitle: 'Gestión de analítica clínica y reportes',
    new: 'Nuevo Resultado',
    import: 'Importar Resultados',
    searchPlaceholder: 'Buscar por paciente o examen...',
    table: {
      date: 'Fecha',
      patient: 'Paciente',
      test: 'Prueba / Examen',
      results: 'Resultados',
      status: 'Estado',
      exam: 'Examen'
    },
    status: {
      pending: 'En Proceso',
      completed: 'Completado',
      ready: 'Listo / Validado',
      delivered: 'Entregado'
    },
    types: {
      blood: 'Sangre',
      urine: 'Orina',
      imaging: 'Imagen / RX'
    },
    examType: 'Tipo de Examen'
  },
  lab_catalog: {
    title: 'Catálogo de Exámenes',
    subtitle: 'Configuración de pruebas, perfiles y lista de precios',
    newTest: 'Nuevo Examen',
    newCombo: 'Nuevo Combo/Perfil',
    commonTests: 'Exámenes Comunes (Venezuela)',
    addCommon: 'Agregar Seleccionados',
    bulkImport: 'Carga Masiva',
    tabs: {
      tests: 'Exámenes Individuales',
      combos: 'Combos y Perfiles'
    },
    testsTab: 'Exámenes Individuales',
    combosTab: 'Combos y Perfiles',
    rateInfo: 'Tasa de Referencia',
    rateDetail: 'Monto en Bs. calculado según tasa oficial BCV:',
    showingInUsd: 'Precios en USD',
    showingInVes: 'Precios en Bs.S',
    table: {
      category: 'Categoría / Examen',
      price: 'Precio (USD)',
      status: 'Estado',
      actions: 'Acciones'
    },
    active: 'Activo',
    inactive: 'Inactivo',
    noTests: 'No hay exámenes registrados.',
    searchHint: 'Intente con otro término o agregue uno nuevo.',
    noCombos: 'No hay combos o perfiles registrados.',
    comboHint: 'Busque por nombre o exámenes incluidos.',
    includes: 'Incluye:',
    comboPrice: 'Precio Combo',
    modals: {
      editTest: 'Editar Examen',
      newTest: 'Nuevo Examen',
      testName: 'Nombre del Examen',
      price: 'Precio (USD)',
      category: 'Categoría',
      description: 'Descripción (Opcional)',
      editCombo: 'Editar Combo/Perfil',
      newCombo: 'Nuevo Combo/Perfil',
      comboName: 'Nombre del Combo',
      suggestedPrice: 'Precio Total Sugerido (USD)',
      selectTests: 'Seleccionar Exámenes Incluidos',
      importTitle: 'Importar Exámenes (CSV)',
      importText: 'Seleccione un archivo CSV con las columnas: name, price, category, description.',
      importSuccess: 'Importación Finalizada',
      imported: 'Exitosos',
      failed: 'Fallidos'
    }
  },
  staff_list: {
    title: 'Personal Administrativo',
    subtitle: 'Gestión de roles administrativos, recepcionistas y personal operativo',
    new: 'Nuevo Personal',
    searchPlaceholder: 'Buscar por nombre, cargo o dpto...',
    allDepartments: 'Todos los departamentos',
    table: {
      staff: 'Personal',
      employeeId: 'ID Empleado',
      position: 'Cargo',
      department: 'Departamento'
    },
    noResults: 'No se encontraron miembros del personal',
    departments: {
      administration: 'Administración',
      reception: 'Recepción',
      accounting: 'Contabilidad',
      hr: 'Recursos Humanos',
      generalServices: 'Servicios Generales',
      security: 'Seguridad',
      maintenance: 'Mantenimiento',
      systems: 'Sistemas'
    }
  },
  bulk_import: {
    title: 'Carga Masiva de Datos',
    subtitle: 'Importación de registros mediante archivos CSV',
    config: 'Configuración de Importación',
    step1: '1. Seleccione el tipo de datos',
    patients: 'Pacientes',
    doctors: 'Doctores',
    lab_catalog: 'Catálogo Lab',
    step2: '2. Descargue la plantilla (opcional)',
    templateDesc: 'Asegúrese de que su archivo siga el formato de nuestra plantilla para evitar errores durante la carga.',
    downloadTemplate: 'Descargar Plantilla CSV',
    step3: '3. Seleccione el archivo CSV',
    fileReady: 'Archivo seleccionado',
    startImport: 'Iniciar Carga Masiva',
    processing: 'Procesando...',
    status: 'Estado de la Carga',
    emptyLabel: 'Seleccione un archivo para comenzar la importación',
    analyzing: 'Analizando el archivo...',
    analyzingDesc: 'Estamos validando los registros antes de guardarlos en el sistema.',
    summary: 'Resumen de la operación',
    importSummary: 'Carga Finalizada: {{success}} exitosos, {{errors}} fallidos.',
    success: 'Exitosos',
    failed: 'Errores',
    errorDetail: 'Detalle de Errores',
    failedRecord: 'Registro fallido',
    finished: '¡Importación Finalizada!',
    selectFileError: 'Por favor seleccione un archivo .csv para continuar',
    importError: 'Error al procesar la carga masiva. Intente de nuevo.',
    template_filename: 'plantilla_importacion'
  },
  landing: {
    title: 'La Plataforma de Gestión Médica',
    subtitle: 'Más Avanzada del Mundo',
    description: 'Centralice su consulta, gestione historias médicas digitales y ofrezca videoconsultas premium con tecnología WebRTC de última generación.',
    pricing: 'Planes y Precios',
    pricingDesc: 'Desde gratuito hasta profesional',
    security: 'Seguridad ISO',
    securityDesc: 'Datos cifrados y blindaje legal',
    reminders: 'Recordatorios',
    remindersDesc: 'Alertas automáticas por WhatsApp',
    loginTitle: 'Acceso a la Plataforma',
    loginDesc: 'Ingresa tus credenciales para continuar',
    forgotPassword: '¿Olvidó su contraseña?',
    enterSystem: 'Entrar al Sistema',
    noAccount: '¿No tienes una cuenta aún?',
    registerHere: 'Regístrate aquí',
    publicBooking: 'Agendar Cita (Público)',
    businessName: 'Nombre del Centro / Consultorio',
    businessNamePlaceholder: 'Ej: Centro Médico San José',
    professional: 'Profesional de Salud',
    clinic: 'Clínica / Consultorio',
    hospital: 'Hospital / Centro'
  },
  branding: {
    title: 'Imagen Corporativa & Branding',
    subtitle: 'Personalice la aplicación y los reportes médicos con su identidad institucional.',
    saveChanges: 'Guardar Cambios',
    saving: 'Guardando...',
    generalSettings: 'Ajustes Generales',
    orgName: 'Nombre de la Institución',
    orgPlaceholder: 'Ej: Centro Clínico Los Olivos',
    logo: 'Logo de la Clínica (URL)',
    logoPlaceholder: 'URL de la imagen (PNG transparente recomendado)',
    logoHint: 'Recomendamos usar un logo con fondo transparente y dimensiones de aprox. 200x60px.',
    primaryColor: 'Color Primario de la Aplicación',
    colorHint: 'Este color se aplicará globalmente a botones, encabezados y reportes.',
    previewTitle: 'Previsualización de Informe Médico',
    previewDate: 'Fecha:',
    previewFolio: 'Folio:',
    previewPatient: 'Datos del Paciente',
    previewDiagnosis: 'Diagnóstico Médico',
    previewDiagnosisHint: 'Aquí aparecerá el diagnóstico y los hallazgos clínicos del médico tratante.',
    previewFooter: 'Este informe ha sido generado electrónicamente por',
    success: 'Configuración guardada correctamente.',
    error: 'No se pudo guardar la configuración.'
  },
  patients_list: {
    title: 'Gestión de Pacientes',
    subtitle: 'Listado completo de pacientes registrados y expedientes',
    new: 'Nuevo Paciente',
    searchPlaceholder: 'Buscar por nombre o documento...',
    allGenders: 'Todos los géneros',
    table: {
      patient: 'Paciente',
      document: 'Documento ID',
      gender: 'Género',
      phone: 'Teléfono'
    }
  },
  register: {
    title: 'Crear cuenta en MedicalCare 888',
    join: 'Únete a',
    heroDesc: 'Crea tu cuenta y accede a la mejor plataforma de gestión clínica.',
    easyAgenda: 'Agenda Fácil',
    easyAgendaDesc: 'Reserva tus citas médicas en segundos.',
    digitalHistory: 'Historial Digital',
    digitalHistoryDesc: 'Accede a tu historial médico.',
    whoAreYou: '¿Quién eres?',
    selectAccountType: 'Selecciona el tipo de cuenta',
    completeData: 'Completa tus datos',
    firstName: 'Nombres',
    lastName: 'Apellidos',
    autoPassword: 'Contraseña generada automáticamente',
    autoPasswordDesc: 'Al crear tu cuenta, el sistema generará una contraseña temporal segura que se mostrará en pantalla. Deberás cambiarla en tu primer ingreso.',
    license: 'Colegiatura / Licencia',
    address: 'Dirección',
    bloodType: 'Tipo de Sangre',
    allergies: 'Alergias',
    acceptTerms: 'Acepto los términos. Datos bajo ISO 27001, ISO 9001 y GDPR.',
    patient: 'Paciente',
    patientDesc: 'Accede a tus citas y expediente médico.',
    professionalDesc: 'Gestiona tu consulta y pacientes.',
    clinicDesc: 'Administra tu clínica completa.',
    hospitalDesc: 'Gestión hospitalaria centralizada.',
    error: 'Error al registrar'
  },
  public_booking: {
    title: 'Agendar Cita Médica',
    subtitle: 'Reserva tu consulta en minutos, sin necesidad de cuenta',
    backToLogin: 'Volver al Login',
    steps: {
      personal: 'Datos Personales',
      appointment: 'Datos de la Cita'
    },
    personalInfo: {
      title: 'Información Personal',
      firstName: 'Nombre',
      lastName: 'Apellido',
      email: 'Correo Electrónico',
      phone: 'Teléfono (WhatsApp)',
      document: 'Cédula / Pasaporte',
      placeholders: {
        firstName: 'Ej: Juan',
        lastName: 'Ej: Pérez',
        email: 'correo@ejemplo.com',
        phone: '04121234567',
        document: 'V-12345678'
      }
    },
    appointmentInfo: {
      title: 'Detalles de la Cita',
      doctor: 'Especialista',
      doctorPlaceholder: 'Seleccione un especialista',
      date: 'Fecha de la Cita',
      time: 'Hora',
      timePlaceholder: 'Seleccione una hora',
      reason: 'Motivo de Consulta',
      reasonPlaceholder: 'Ej: Control General, Revisión...',
      notes: 'Notas Adicionales (Opcional)',
      notesPlaceholder: 'Cualquier información relevante...'
    },
    actions: {
      continue: 'Continuar',
      back: 'Volver',
      confirm: 'Confirmar y Agendar',
      booking: 'Agendando...',
      hasAccount: '¿Ya tienes cuenta?',
      loginNow: 'Iniciar Sesión'
    },
    errors: {
      required: 'Este campo es obligatorio',
      email: 'Ingresa un correo electrónico válido',
      minlength: 'Demasiado corto',
      pattern: 'Formato inválido',
      invalidDate: 'Fecha no válida',
      selectDoctor: 'Selecciona un especialista',
      selectTime: 'Selecciona una hora',
      general: 'Ocurrió un error al agendar la cita. Intenta de nuevo.'
    },
    success: {
      title: '¡Cita Agendada!',
      msg: 'Tu cita ha sido registrada exitosamente.',
      notification: 'Recibirás una confirmación por WhatsApp.',
      calendar: 'Agregar al Calendario',
      didYouKnow: '¿Sabías que puedes crear una cuenta?',
      accountBenefits: 'Con una cuenta puedes ver tu historial, gestionar tus citas y mucho más.',
      createAccount: 'Crear Cuenta Gratis',
      gotIt: 'Entendido'
    }
  },
  subscription: {
    pricingTitle: 'Planes y Precios',
    choosePlan: 'Elija su Plan Perfecto',
    scalePlan: 'Escale su práctica médica con nosotros',
    trialTitle: 'Prueba de 14 Días Gratis',
    trialDesc: 'Pruebe todas las funciones premium de MedicalCare 888 sin costo inicial. Sin tarjeta de crédito.',
    startTrial: 'Comenzar Prueba Gratis',
    activeSession: 'Sesión Activa - Gestión de Plan',
    recommended: 'Recomendado',
    monthly: 'Mensual',
    choosePlanBtn: 'Elegir este Plan',
    currentPlan: 'Tu Plan Actual',
    customDeployment: 'Despliegue a Medida (Enterprise)',
    customDeploymentDesc: 'Soporte premium para grandes instituciones y redes hospitalarias.',
    supportEmail: 'Correo de Soporte Técnico'
  }
};

const EN_DICT = {
  common: {
    search: 'Search...',
    actions: 'Actions',
    status: 'Status',
    save: 'Save',
    cancel: 'Cancel',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    noResults: 'No results found',
    doctor: 'Doctor',
    birthDate: 'Birth Date',
    username: 'Username',
    confirm: 'Confirm',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    filters: 'Filters',
    advancedFilters: 'Advanced Filters',
    clearFilters: 'Clear Filters',
    resultsOf: 'Showing {{count}} of {{total}} records',
    select: 'Select...',
    back: 'Back',
    dashboard: 'Main Dashboard',
    printing: 'Print/Download',
    active: 'Active',
    inactive: 'Inactive'
  },
  auth: {
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    logoutConfirm: 'Logout?',
    logoutText: 'You will have to enter your credentials again.',
    logoutYes: 'Yes, logout',
    logoutCancel: 'Cancel',
    welcome: 'Welcome!',
    email: 'Email',
    password: 'Password'
  },
  video_history: {
    sidebar: 'Video Consultations',
    title: 'Video Consultation History',
    subtitle: 'Consult and manage the historical record of your medical videocalls.',
    refresh: 'Refresh',
    loadError: 'Could not load video consultation history.',
    noResults: 'No Video Consultations',
    noResultsDesc: 'You don\'t have any videocall records yet. You can schedule a new consultation from the appointments module.',
    goToAppointments: 'Go to My Appointments',
    patient: 'Patient',
    doctor: 'Doctor',
    duration: 'Duration',
    consultNotes: 'Consultation Notes',
    downloadReport: 'Download Report',
    joinCall: 'Join Call',
    status: {
      scheduled: 'Scheduled',
      active: 'Active',
      completed: 'Completed',
      cancelled: 'Cancelled'
    },
    reportTitle: 'MEDICAL VIDEO CONSULTATION REPORT',
    telemedPlatform: 'Telemedicine Platform',
    sessionDetails: 'SESSION DETAILS',
    treatingDoctor: 'Treating Doctor',
    date: 'Date',
    minutes: 'minutes',
    clinicalNotes: 'CLINICAL FINDINGS & NOTES',
    generatedOn: 'Report generated on'
  },
  team: {
    sidebar: 'Team Management',
    title: 'Clinic Staff',
    subtitle: 'Management of team members and roles for administrative and medical staff',
    addMember: 'Add Member',
    newMember: 'New Team Member',
    member: 'Member',
    role: 'Role',
    selectRole: 'Select a role',
    license: 'License Number',
    gender: 'Gender',
    invitationButton: 'Send Invitation',
    noMembers: 'No members registered yet.',
    messages: {
      loading: 'Processing...',
      success: 'Member added and welcome email sent.',
      confirmDelete: 'Remove member?',
      confirmDeleteText: 'The user will lose access to the platform.',
      yesDelete: 'Confirm Removal'
    }
  },
  billing: {
    sidebar: 'My Subscription',
    title: 'My Subscription & Billing',
    subtitle: 'Manage your plan, payment methods, and transaction history',
    updatePlan: 'Update Plan',
    timeRemaining: 'Time remaining',
    days: 'days',
    expiresOn: 'Expires on:',
    reminderNotice: 'Keep your payments up to date to avoid service interruption.',
    paymentHistory: 'Payment History',
    noPayments: 'No recent payments found in your history.',
    table: {
      date: 'Date',
      concept: 'Concept',
      method: 'Method / Bank',
      amount: 'Amount',
      status: 'Status',
      receipt: 'Receipt / PDF'
    }
  },
  payments: {
    title: 'Payment Control',
    subtitle: 'Billing management and account statements',
    newPayment: 'New Transaction',
    export: 'Export Report',
    reference: 'Reference',
    patient: 'Patient',
    concept: 'Concept',
    amount: 'Amount',
    fecha: 'Date',
    collect: 'Collect',
    receipt: 'Receipt',
    pending: 'Pending',
    paid: 'Paid',
    doctorConsultation: 'Consultation / Doctor',
    generalPayment: 'General Payment',
    edit: 'Edit Payment',
    delete: 'Delete Payment',
    registerTitle: 'Register New Payment',
    editTitle: 'Edit Appointment Payment',
    payCurrency: 'Payment Currency',
    bankPlatform: 'Bank / Platform',
    updateReceipt: 'Update Receipt (Optional)',
    hasAttachment: 'This payment already has a receipt attached.',
    selectAppointment: 'Select Appointment',
    method: 'Payment Method',
    select: 'Select an option',
    bankPlatformPlaceholder: 'e.g. Banesco, Mercantil, Zelle...',
    refPlaceholder: 'Receipt number or reference',
    payDate: 'Payment Date',
    attachReceipt: 'Attach Receipt',
    saveChanges: 'Save Changes',
    confirmDelete: 'Delete Payment?',
    confirmDeleteText: 'This action cannot be undone.',
    yesDelete: 'Yes, delete',
    deleted: 'Deleted',
    deletedMsg: 'The payment has been deleted.',
    updated: 'Updated!',
    updatedMsg: 'The payment has been successfully updated.',
    viewReceipt: 'View Receipt / Voucher',
    subscriptionPayment: 'Register Subscription Payment (Plan)',
    patientPayment: 'Register Patient Payment',
    selectRole: 'Payment Type',
    onboardingTitle: 'Subscription Payment',
    onboardingSuccess: 'Payment registered successfully.',
    onboardingRegister: 'Now, complete your registration to activate your account.',
    goToRegister: 'Go to Registration',
    onboardingExisting: 'Renewal payment registered successfully. Your plan will be activated shortly.'
  },
  medical_history: {
    title: 'Digital Medical History',
    subtitle: 'Complete and chronological clinical record of the patient',
    selectPatient: 'Select a patient to view their history',
    id: 'ID/Document',
    phone: 'Phone',
    gender: 'Gender',
    newRecord: 'New Consultation / Evolution',
    changePatient: 'Change Patient',
    physicalExam: 'Physical Exam / Reason',
    treatment: 'Suggested Treatment',
    diagnosis: 'Clinical Diagnosis',
    indications: 'Medical Indications',
    save: 'Save Consultation',
    print: 'Print Report',
    export: 'Export History',
    examPlaceholder: 'Vital signs, physical findings...',
    treatmentPlaceholder: 'Medications and procedures...',
    indicationsPlaceholder: 'Rest, diet, care...',
    medicalLeave: 'Medical Leave / Certificate',
    leaveDays: 'Leave days',
    startDate: 'Start Date',
    endDate: 'End Date (Estimated)',
    tabs: {
      consultations: 'Consultations',
      labs: 'Laboratory',
      treatments: 'Treatments'
    },
    prescription: {
      title: 'Medical Prescription (Rp)',
      search: 'Search medication...',
      drug: 'Medication',
      dosage: 'Dosage',
      frequency: 'Frequency',
      duration: 'Duration',
      empty: 'No medications added to the prescription'
    }
  },
  sidebar: {
    medicalManagement: 'MEDICAL MANAGEMENT',
    appointments: 'Appointments',
    history: 'Patient History',
    patients: 'Patients',
    lab: 'Laboratory',
    medicalStaff: 'MEDICAL STAFF',
    doctors: 'Doctors',
    nurses: 'Nursing',
    drugGuide: 'Drug Guide',
    administration: 'ADMINISTRATION',
    staff: 'My Staff',
    payments: 'Payments Control',
    config: 'CONFIGURATION',
    bulkData: 'Bulk Import',
    myTeam: 'Team Management',
    billing: 'My Subscription',
    dashboard: 'Main Dashboard',
    labCatalog: 'Lab Catalog',
    branding: 'Corporate Brand'
  },
  navbar: {
    updateInfo: 'Update Information',
    changePassword: 'Change Password',
    logout: 'Logout',
    updateRate: 'Update BCV Rate',
    rateHint: 'Official Central Bank Rate'
  },
  roles: {
    SUPERADMIN: 'Super Administrator',
    ADMINISTRATIVE: 'Administrative Staff',
    DOCTOR: 'Medical Specialist',
    NURSE: 'Nursing Staff',
    PATIENT: 'Patient',
    RECEPTIONIST: 'Receptionist'
  },
  drug_guide: {
    title: 'Digital Drug Guide',
    subtitle: 'Complete vademecum of medications and dosage',
    newDrug: 'New Medication',
    vademecumLabel: 'External Vademecum Query',
    vademecumDesc: 'Direct link to the official pharmaceutical database.',
    vademecumLink: 'Go to Vademecum',
    searchPlaceholder: 'Search by name, active ingredient...',
    search: 'Search',
    allCategories: 'All categories',
    noResults: 'No medications found',
    noResultsHint: 'Try another term or add a new one to the database.',
    results: 'results',
    validation: 'Please fill in all required fields',
    savedOk: 'Drug saved successfully',
    confirmDelete: 'Delete Medication',
    confirmDeleteText: 'Are you sure you want to delete {{name}}? This action cannot be undone.',
    yes: 'Yes, delete',
    no: 'Cancel',
    deletedOk: 'Drug deleted successfully',
    noCategory: 'No category',
    table: {
      commercial: 'Commercial Name',
      generic: 'Generic Name',
      components: 'Components',
      presentation: 'Presentation',
      category: 'Category',
      actions: 'Actions'
    },
    detail: {
      edit: 'Edit',
      close: 'Close',
      presentation: 'Presentation',
      category: 'Category',
      components: 'Active Components',
      indications: 'Indications',
      posology: 'Dosage',
      contraindications: 'Contraindications',
      adverseReactions: 'Adverse Reactions',
      precautions: 'Precautions',
      noSpecified: 'Not specified'
    },
    form: {
      create: 'New Medication',
      edit: 'Edit Medication',
      commercial: 'Commercial Name',
      commercialPlaceholder: 'e.g: Panadol',
      generic: 'Generic Name',
      genericPlaceholder: 'e.g: Paracetamol',
      components: 'Active Components',
      componentsPlaceholder: 'e.g: Acetaminophen 500mg',
      componentsHint: 'Active ingredients separated by comma',
      presentation: 'Presentation',
      presentationPlaceholder: 'e.g: Tablets 500mg',
      category: 'Category',
      categoryPlaceholder: 'Select or type a category',
      indications: 'Indications',
      indicationsPlaceholder: 'What this medication is used for...',
      posology: 'Dosage',
      posologyPlaceholder: 'Recommended dose and frequency...',
      contraindications: 'Contraindications',
      contraindicationsPlaceholder: 'When it should not be used...',
      adverseReactions: 'Adverse Reactions',
      adverseReactionsPlaceholder: 'Known side effects...',
      precautions: 'Precautions',
      precautionsPlaceholder: 'Warnings and precautions...',
      cancel: 'Cancel',
      save: 'Save',
      create_btn: 'Create'
    }
  },
  dashboard: {
    controlPanel: 'Control Panel',
    welcome: 'Welcome back',
    reportBtn: 'Download Report',
    newAppointment: 'New Appointment',
    activity: 'Appointment Activity',
    upcoming: 'Upcoming Appointments',
    days7: 'Last 7 days',
    stats: {
      totalPatients: 'Total Patients',
      income: 'Total Income',
      pending: 'Pending Appointments',
      videoCalls: 'Video Calls',
      inPerson: 'In-Person Appointments',
      appointments: 'Appointments',
      specialtyBreakdown: 'Specialty Breakdown',
      incomeAnalysis: 'Income Analysis',
      daily: 'Daily Income',
      weekly: 'Weekly Income',
      monthly: 'Monthly Income',
      today: 'Appointments Today',
      patients: 'Total Patients',
      video: 'Video Consultations (Month)',
      incomeUSD: 'Income USD (Month)',
      incomeBs: 'Income Bs (Month)'
    },
    specialties: {
      pediatrics: 'Pediatrics',
      general: 'General Medicine',
      dentistry: 'Dentistry',
      cardiology: 'Cardiology',
      gynecology: 'Gynecology',
      traumatology: 'Traumatology',
      dermatology: 'Dermatology',
      neurology: 'Neurology',
      ophthalmology: 'Ophthalmology',
      psychiatry: 'Psychiatry'
    },
    report: {
      stat: 'Statistic',
      value: 'Value',
      title: 'Activity Report - MedicalCare 888',
      tagline: 'Professional Clinical Management',
      specialtyPerf: 'Specialty Performance',
      pending: 'Pend',
      attended: 'Attend'
    },
    export: {
      title: 'Export Report',
      text: 'Select download format'
    },
    redirecting: 'Redirecting to the appointments module...',
    trial: {
      daysRemaining: 'Your free trial ends in {{days}} days',
      trialDesc: 'Full access to all premium features enabled.',
      upgradePlan: 'Upgrade Plan Now'
    },
    confirmed: 'Confirmed',
    reminderSent: 'Reminder Sent',
    active: 'Active',
    inactive: 'Inactive'
  },
  appointments_list: {
    title: 'Appointment Scheduling',
    subtitle: 'Management of consultations and waiting list',
    newTitle: 'New Appointment',
    editTitle: 'Edit Appointment',
    today: 'Today\'s Appointments',
    all: 'All Appointments',
    pending: 'Pending',
    completed: 'Completed',
    cancelled: 'Cancelled',
    table: {
      patient: 'Patient',
      doctor: 'Doctor',
      date: 'Date & Time',
      status: 'Status',
      reason: 'Reason'
    },
    actions: {
      confirm: 'Confirm Attendance',
      cancel: 'Cancel Appointment',
      reschedule: 'Reschedule',
      startConsultation: 'Start Consultation'
    },
    filterSpecialty: 'Filter by Specialty',
    whatsappService: 'WhatsApp Service',
    serviceActive: 'Service Active',
    time: 'Appointment Time',
    reason: 'Consultation Reason',
    reasonPlaceholder: 'e.g. Monthly Control, Checkup...',
    notes: 'Additional Notes',
    videoCall: 'Video Call',
    scheduled: 'Scheduled Appointments',
    whatsappDesc: 'Automatic reminders for your patients',
    tabs: {
      day: 'Today',
      week: 'Week',
      month: 'Month'
    },
    new: 'New Appointment'
  },
  doctors: {
    title: 'Specialists Management',
    subtitle: 'Complete list of doctors and healthcare professionals',
    new: 'New Doctor',
    searchPlaceholder: 'Search by name or specialty...',
    allSpecialties: 'All specialties',
    viewProfile: 'View Profile',
    schedule: 'View Schedule',
    noResults: 'No doctors found with the search criteria.',
    active: 'Active',
    inactive: 'Inactive',
    available: 'Available',
    fields: {
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email',
      phone: 'Phone',
      license: 'Medical License',
      specialty: 'Specialty',
      password: 'Password',
      passwordPlaceholder: 'Minimum 6 characters'
    },
    messages: {
      completeRequired: 'Please complete all fields',
      created: 'Doctor Created!',
      createdMsg: 'The doctor has been successfully registered in the system.',
      confirmDelete: 'Delete Doctor?',
      confirmDeleteMsg: 'The doctor will no longer have access to the system.',
      deleteConfirmBtn: 'Delete',
      deleted: 'Deleted',
      deletedMsg: 'The doctor has been removed from the system.',
      toggleStatus: '{action} Doctor?',
      toggleStatusMsg: 'Doctor {name} will be {status} in the system.',
      toggleBypass: '{action} Bypass?',
      toggleBypassMsg: 'Doctor {name} will {action2} subscription limits.',
      toggleBypassTooltip: 'Subscription Bypass (VIP)'
    }
  },
  nurses: {
    title: 'Nursing Staff',
    subtitle: 'Shift management and nursing assignments',
    new: 'New Nurse',
    table: {
      nurse: 'Nurse',
      specialty: 'Specialty',
      shift: 'Shift',
      license: 'License'
    },
    noResults: 'No nurses found.',
    searchPlaceholder: 'Search nurse...',
    allShifts: 'All shifts',
    filters: 'Filters',
    showing: 'Showing',
    of: 'of',
    filtersCleared: 'Filters Cleared',
    filtersClearedMsg: 'All search filters have been reset.',
    fields: {
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email',
      phone: 'Phone',
      license: 'License Number',
      shift: 'Shift',
      specialization: 'Specialty',
      password: 'Password',
      passwordPlaceholder: 'Minimum 6 characters'
    },
    shifts: {
      morning: 'Morning',
      afternoon: 'Afternoon',
      night: 'Night',
      rotating: 'Rotating'
    },
    specialties: {
      general: 'General Nursing',
      icu: 'Intensive Care',
      pediatrics: 'Pediatrics',
      surgery: 'Surgery',
      emergency: 'Emergency',
      geriatrics: 'Geriatrics',
      neonatology: 'Neonatology',
      oncology: 'Oncology'
    },
    messages: {
      completeRequired: 'Please complete all required fields.',
      created: 'Nurse Created',
      createdMsg: 'The record has been successfully created.',
      confirmDelete: 'Are you sure?',
      confirmDeleteText: 'This action cannot be undone.',
      yesDelete: 'Yes, delete',
      deleted: 'Deleted',
      deletedMsg: 'The record has been deleted.',
      errorDelete: 'Could not delete the record.'
    }
  },
  booking: {
    personalInfo: 'Personal Information',
    firstName: 'First Name',
    lastName: 'Last Name',
    docId: 'ID / Passport',
    gender: 'Gender',
    phone: 'Phone',
    birthDate: 'Birth Date',
    address: 'Address',
    appointmentInfo: 'Appointment Details',
    specialty: 'Specialty',
    doctor: 'Specialist',
    date: 'Appointment Date',
    reason: 'Reason for Visit',
    additionalNotes: 'Additional Notes (Optional)',
    submit: 'Book Medical Appointment',
    successTitle: 'Appointment Booked!',
    successMsg: 'Your appointment has been successfully registered. You will receive a confirmation email.',
    errorTitle: 'Error',
    errorMsg: 'Could not book the appointment. Please check the data.',
    placeholders: {
      firstName: 'e.g. John',
      lastName: 'e.g. Smith',
      docId: 'e.g. 12345678',
      phone: 'e.g. 04121234567',
      address: 'City, Neighborhood...',
      reason: 'e.g. General Consultation, Checkup...',
      notes: 'Any additional information you want to share...',
      specialty: 'Select a specialty',
      doctor: 'Select a specialist'
    }
  },
  lab: {
    title: 'Laboratory Results',
    subtitle: 'Clinical analytics and reports management',
    new: 'New Result',
    import: 'Import Results',
    searchPlaceholder: 'Search by patient or exam...',
    table: {
      date: 'Date',
      patient: 'Patient',
      test: 'Test / Exam',
      results: 'Results',
      status: 'Status',
      exam: 'Exam'
    },
    status: {
      pending: 'In Process',
      completed: 'Completed',
      ready: 'Ready / Validated',
      delivered: 'Delivered'
    },
    types: {
      blood: 'Blood',
      urine: 'Urine',
      imaging: 'Imaging / RX'
    },
    examType: 'Test Type'
  },
  lab_catalog: {
    title: 'Test Catalog',
    subtitle: 'Setup trials, profiles and price list',
    newTest: 'New Test',
    newCombo: 'New Combo/Profile',
    commonTests: 'Common Tests (Venezuela)',
    addCommon: 'Add Selected',
    bulkImport: 'Bulk Import',
    tabs: {
      tests: 'Individual Tests',
      combos: 'Combos and Profiles'
    },
    testsTab: 'Individual Tests',
    combosTab: 'Combos and Profiles',
    rateInfo: 'Reference Rate',
    rateDetail: 'Amount in Bs. calculated according to official BCV rate:',
    showingInUsd: 'Prices in USD',
    showingInVes: 'Prices in Bs.S',
    table: {
      category: 'Category / Test',
      price: 'Price (USD)',
      status: 'Status',
      actions: 'Actions'
    },
    active: 'Active',
    inactive: 'Inactive',
    noTests: 'No tests registered.',
    searchHint: 'Try another term or add a new one.',
    noCombos: 'No combos or profiles registered.',
    comboHint: 'Search by name or included tests.',
    includes: 'Includes:',
    comboPrice: 'Combo Price',
    modals: {
      editTest: 'Edit Test',
      newTest: 'New Test',
      testName: 'Test Name',
      price: 'Price (USD)',
      category: 'Category',
      description: 'Description (Optional)',
      editCombo: 'Edit Combo/Profile',
      newCombo: 'New Combo/Profile',
      comboName: 'Combo Name',
      suggestedPrice: 'Suggested Total Price (USD)',
      selectTests: 'Select Included Tests',
      importTitle: 'Import Tests (CSV)',
      importText: 'Select a CSV file with columns: name, price, category, description.',
      importSuccess: 'Import Finished',
      imported: 'Successful',
      failed: 'Failed'
    }
  },
  staff_list: {
    title: 'Staff Members',
    subtitle: 'Management of administrative roles, receptionists, and operational staff',
    new: 'New Staff Member',
    searchPlaceholder: 'Search by name, position or department...',
    allDepartments: 'All departments',
    table: {
      staff: 'Staff',
      employeeId: 'Employee ID',
      position: 'Position',
      department: 'Department'
    },
    noResults: 'No staff members found',
    departments: {
      administration: 'Administration',
      reception: 'Reception',
      accounting: 'Accounting',
      hr: 'Human Resources',
      generalServices: 'General Services',
      security: 'Security',
      maintenance: 'Maintenance',
      systems: 'IT / Systems'
    }
  },
  bulk_import: {
    title: 'Bulk Data Import',
    subtitle: 'Import records via CSV files',
    config: 'Import Configuration',
    step1: '1. Select data type',
    patients: 'Patients',
    doctors: 'Doctors',
    lab_catalog: 'Lab Catalog',
    step2: '2. Download template (optional)',
    templateDesc: 'Make sure your file follows our template format to avoid errors during upload.',
    downloadTemplate: 'Download CSV Template',
    step3: '3. Select CSV file',
    fileReady: 'File selected',
    startImport: 'Start Bulk Import',
    processing: 'Processing...',
    status: 'Upload Status',
    emptyLabel: 'Select a file to begin import',
    analyzing: 'Analyzing file...',
    analyzingDesc: 'We are validating records before saving them to the system.',
    summary: 'Operation Summary',
    importSummary: 'Import Finished: {{success}} successful, {{errors}} failed.',
    success: 'Successful',
    failed: 'Errors',
    errorDetail: 'Error Detail',
    failedRecord: 'Failed Record',
    template_filename: 'template'
  },
  landing: {
    title: 'The Most Advanced Medical',
    subtitle: 'Management Platform',
    description: 'Centralize your practice, manage digital medical records, and offer premium video consultations with state-of-the-art WebRTC technology.',
    pricing: 'Plans & Pricing',
    pricingDesc: 'From free to professional',
    security: 'ISO Security',
    securityDesc: 'Encrypted data and legal shield',
    reminders: 'Reminders',
    remindersDesc: 'Automatic WhatsApp alerts',
    loginTitle: 'Platform Access',
    loginDesc: 'Enter your credentials to continue',
    forgotPassword: 'Forgot your password?',
    enterSystem: 'Enter System',
    noAccount: 'Don\'t have an account yet?',
    registerHere: 'Register here',
    publicBooking: 'Book Appointment (Public)',
    businessName: 'Center / Clinic Name',
    businessNamePlaceholder: 'e.g. San Jose Medical Center',
    professional: 'Health Professional',
    clinic: 'Clinic / Practice',
    hospital: 'Hospital / Center'
  },
  patients_list: {
    title: 'Patient Management',
    subtitle: 'Complete list of registered patients and records',
    new: 'New Patient',
    searchPlaceholder: 'Search by name or document...',
    allGenders: 'All genders',
    table: {
      patient: 'Patient',
      document: 'ID Document',
      gender: 'Gender',
      phone: 'Phone'
    }
  },
  register: {
    title: 'Create account in MedicalCare 888',
    join: 'Join',
    heroDesc: 'Create your account and access the best clinical management platform.',
    easyAgenda: 'Easy Booking',
    easyAgendaDesc: 'Book your medical appointments in seconds.',
    digitalHistory: 'Digital Records',
    digitalHistoryDesc: 'Access your medical history.',
    whoAreYou: 'Who are you?',
    selectAccountType: 'Select account type',
    completeData: 'Complete your data',
    firstName: 'First Name',
    lastName: 'Last Name',
    autoPassword: 'Automatically generated password',
    autoPasswordDesc: 'When creating your account, the system will generate a secure temporary password that will be displayed on screen. You must change it upon your first login.',
    license: 'Medical License / Number',
    address: 'Address',
    bloodType: 'Blood Type',
    allergies: 'Allergies',
    acceptTerms: 'I accept the terms. Data under ISO 27001, ISO 9001, and GDPR compliance.',
    patient: 'Patient',
    patientDesc: 'Access your appointments and medical record.',
    professionalDesc: 'Manage your practice and patients.',
    clinicDesc: 'Manage your full clinic operations.',
    hospitalDesc: 'Centralized hospital management.',
    error: 'Registration error'
  },
  public_booking: {
    title: 'Book Medical Appointment',
    subtitle: 'Reserve your consultation in minutes, no account needed',
    backToLogin: 'Back to Login',
    steps: {
      personal: 'Personal Info',
      appointment: 'Appointment'
    },
    personalInfo: {
      title: 'Personal Information',
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email Address',
      phone: 'Phone (WhatsApp)',
      document: 'ID / Passport',
      placeholders: {
        firstName: 'e.g. John',
        lastName: 'e.g. Smith',
        email: 'email@example.com',
        phone: '+1 555-1234567',
        document: '12345678'
      }
    },
    appointmentInfo: {
      title: 'Appointment Details',
      doctor: 'Specialist',
      doctorPlaceholder: 'Select a specialist',
      date: 'Appointment Date',
      time: 'Time',
      timePlaceholder: 'Select a time slot',
      reason: 'Reason for Visit',
      reasonPlaceholder: 'e.g. General Checkup, Follow-up...',
      notes: 'Additional Notes (Optional)',
      notesPlaceholder: 'Any relevant information...'
    },
    actions: {
      continue: 'Continue',
      back: 'Back',
      confirm: 'Confirm & Book',
      booking: 'Booking...',
      hasAccount: 'Already have an account?',
      loginNow: 'Log In'
    },
    errors: {
      required: 'This field is required',
      email: 'Please enter a valid email address',
      minlength: 'Too short',
      pattern: 'Invalid format',
      invalidDate: 'Invalid date',
      selectDoctor: 'Please select a specialist',
      selectTime: 'Please select a time slot',
      general: 'An error occurred while booking the appointment. Please try again.'
    },
    success: {
      title: 'Appointment Booked!',
      msg: 'Your appointment has been successfully registered.',
      notification: 'You will receive a WhatsApp confirmation.',
      calendar: 'Add to Calendar',
      didYouKnow: 'Did you know you can create an account?',
      accountBenefits: 'With an account you can view your history, manage appointments and more.',
      createAccount: 'Create Free Account',
      gotIt: 'Got it'
    }
  },
  subscription: {
    pricingTitle: 'Plans & Pricing',
    choosePlan: 'Choose Your Perfect Plan',
    scalePlan: 'Scale your medical practice with us',
    trialTitle: '14-Day Free Trial',
    trialDesc: 'Try all MedicalCare 888 premium features at no initial cost. No credit card required.',
    startTrial: 'Start Free Trial',
    activeSession: 'Active Session - Plan Management',
    recommended: 'Recommended',
    monthly: 'Monthly',
    choosePlanBtn: 'Choose this Plan',
    currentPlan: 'Your Current Plan',
    customDeployment: 'Custom Deployment (Enterprise)',
    customDeploymentDesc: 'For hospital networks and large medical centers, we offer solutions on dedicated servers.',
    supportEmail: 'Technical Support Email'
  },
  branding: {
    title: 'Corporate Identity & Branding',
    subtitle: 'Customize the application and medical reports with your institutional identity.',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    generalSettings: 'General Settings',
    orgName: 'Institution Name',
    orgPlaceholder: 'e.g., Los Olivos Clinical Center',
    logo: 'Clinic Logo (URL)',
    logoPlaceholder: 'Image URL (transparent PNG recommended)',
    logoHint: 'We recommend using a logo with a transparent background and dimensions of approx. 200x60px.',
    primaryColor: 'Primary Application Color',
    colorHint: 'This color will be applied globally to buttons, headers, and reports.',
    previewTitle: 'Medical Report Preview',
    previewDate: 'Date:',
    previewFolio: 'Folio:',
    previewPatient: 'Patient Data',
    previewDiagnosis: 'Medical Diagnosis',
    previewDiagnosisHint: 'The treating physician\'s diagnosis and clinical findings will appear here.',
    previewFooter: 'This report has been electronically generated by',
    success: 'Configuration saved successfully.',
    error: 'Could not save configuration.'
  }
};

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private currentLang = signal<Language>('es');
  
  public locale = computed(() => this.currentLang() === 'es' ? 'es-ES' : 'en-US');
  
  private translations: Record<Language, any> = {
    es: ES_DICT,
    en: EN_DICT
  };

  constructor() {
    const savedLang = localStorage.getItem('lang') as Language;
    if (savedLang && (savedLang === 'es' || savedLang === 'en')) {
      this.currentLang.set(savedLang);
    }
  }

  get lang() {
    return this.currentLang.asReadonly();
  }

  setLanguage(lang: Language) {
    this.currentLang.set(lang);
    localStorage.setItem('lang', lang);
  }

  translate(path: string): string {
    const keys = path.split('.');
    let translation = this.translations[this.currentLang()];
    
    for (const key of keys) {
      if (translation && translation[key]) {
        translation = translation[key];
      } else {
        return path;
      }
    }
    
    return translation;
  }
}
